import './globals.css'
import { Ultra, Barlow } from 'next/font/google'

export const ultra = Ultra({weight: ["400"], subsets: ['latin'] })
export const barlow = Barlow({weight: ["400"], subsets: ['latin'],variable: '--font-barlow' })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ultra.className}>{children}</body>
    </html>
  )
}
